import type { Metadata } from "next";
import { buildMetadata } from "./base";

export const homeMetadata: Metadata = buildMetadata({
  title: "Kiranase - Bazaar se Sasta Har Din | 30 Min Delivery in Bihar",
  description:
    "Kiranase delivers fresh groceries, fruits, vegetables, personal care, electronics, Shaadi ka Saman & everything your home needs — cheaper than your local bazaar! 7000+ products across 10,000+ pincodes in India. Delivered in just 30 minutes. Free delivery above ₹299! 🛒",
  keywords: [
    // ==================
    // BRAND KEYWORDS
    // ==================

    // Food & Grocery Brands
    "amul milk delivery bihar",
    "amul dahi online order bihar",
    "amul butter delivery patna",
    "amul cheese online bihar",
    "amul ice cream delivery bihar",
    "patanjali atta online bihar",
    "patanjali products delivery bihar",
    "patanjali ghee online order",
    "patanjali dant kanti online bihar",
    "tata salt online delivery bihar",
    "tata tea online order bihar",
    "tata sampann dal online",
    "fortune oil online delivery bihar",
    "saffola oil delivery bihar",
    "aashirvaad atta online bihar",
    "aashirvaad delivery patna",
    "maggi noodles delivery bihar",
    "nestle products online bihar",
    "britannia biscuits delivery",
    "parle products online bihar",
    "haldiram namkeen delivery bihar",
    "bikaji namkeen online bihar",
    "mother dairy milk bihar",
    "kwality walls ice cream bihar",
    "vim dish wash delivery bihar",
    "surf excel online bihar",
    "ariel detergent delivery bihar",
    "tide detergent online bihar",
    "lifebuoy soap delivery bihar",
    "lux soap online order bihar",
    "clinic plus shampoo bihar",
    "head shoulders delivery bihar",

    // Electronics Brands
    "samsung tv delivery bihar",
    "samsung tv delivery patna",
    "lg tv online order bihar",
    "sony tv delivery bihar",
    "mi tv delivery patna",
    "realme tv online bihar",
    "havells fan delivery bihar",
    "havells fan online order patna",
    "orient fan delivery bihar",
    "usha fan online bihar",
    "crompton fan delivery bihar",
    "bajaj fan online order bihar",
    "atomberg fan delivery bihar",
    "havells cooler delivery bihar",
    "symphony cooler online bihar",
    "voltas cooler delivery patna",
    "bajaj cooler online bihar",
    "philips led bulb delivery bihar",
    "syska led online bihar",
    "havells led delivery bihar",
    "prestige mixer grinder bihar",
    "bajaj mixer online order bihar",
    "philips mixer delivery bihar",
    "kent ro water purifier bihar",
    "aquaguard delivery patna",
    "whirlpool washing machine bihar",
    "samsung refrigerator delivery bihar",
    "lg refrigerator online bihar",
    "voltas ac delivery bihar",
    "daikin ac online order bihar",

    // Personal Care Brands
    "dove soap delivery bihar",
    "dove shampoo online bihar",
    "dettol soap online order bihar",
    "dettol handwash delivery bihar",
    "colgate toothpaste delivery bihar",
    "pepsodent toothpaste online bihar",
    "oral b toothbrush delivery bihar",
    "gillette razor online bihar",
    "nivea cream delivery bihar",
    "pond's cream online bihar",
    "fair lovely online bihar",
    "garnier face wash delivery bihar",
    "himalaya products online bihar",
    "dabur products delivery bihar",
    "dabur honey online order bihar",
    "dabur chyawanprash delivery",
    "parachute coconut oil online bihar",
    "bajaj almond drops delivery",
    "whisper pads online delivery bihar",
    "stayfree delivery bihar",
    "pampers diapers online bihar",
    "huggies delivery patna",

    // ==================
    // PRODUCT KEYWORDS
    // ==================

    // Atta Dal Chawal Oil
    "atta online delivery bihar",
    "gehun atta home delivery",
    "chakki fresh atta online",
    "besan online order bihar",
    "maida delivery bihar",
    "arhar dal online bihar",
    "moong dal delivery bihar",
    "chana dal online order",
    "masoor dal delivery bihar",
    "urad dal online bihar",
    "basmati rice online bihar",
    "chawal online delivery bihar",
    "sona masoori rice delivery",
    "mustard oil online bihar",
    "sarson ka tel delivery bihar",
    "refined oil online order",
    "sunflower oil delivery bihar",
    "ghee online order bihar",
    "desi ghee delivery bihar",
    "sugar online delivery bihar",
    "namak online order bihar",
    "masale online delivery bihar",
    "haldi online order bihar",
    "mirchi powder delivery bihar",

    // Fruits & Vegetables
    "fresh vegetables online bihar",
    "sabji online order bihar",
    "ताजी सब्जी होम डिलीवरी",
    "fresh fruits delivery bihar",
    "fruits online order patna",
    "apple online delivery bihar",
    "banana delivery home bihar",
    "tomato online order bihar",
    "potato onion delivery bihar",
    "aloo pyaz online bihar",
    "green vegetables delivery",
    "organic vegetables bihar",
    "farm fresh sabji delivery",
    "sabzi mandi online bihar",

    // Electronics Products
    "fan delivery home bihar",
    "ceiling fan online bihar",
    "table fan delivery patna",
    "pedestal fan online bihar",
    "cooler delivery home bihar",
    "desert cooler online bihar",
    "air cooler delivery patna",
    "LED TV delivery bihar",
    "smart tv online order bihar",
    "television delivery home bihar",
    "LED bulb online bihar",
    "tube light delivery bihar",
    "inverter battery online bihar",
    "UPS delivery home bihar",
    "electric iron delivery bihar",
    "induction cooktop online bihar",
    "mixer grinder delivery bihar",
    "juicer online order bihar",
    "electric kettle delivery bihar",
    "room heater online bihar",

    // Shaadi ka Saman
    "shaadi ka saman online bihar",
    "शादी का सामान ऑनलाइन बिहार",
    "wedding shopping delivery bihar",
    "shaadi ki khareedari ghar baithe",
    "wedding essentials delivery bihar",
    "shaadi decoration online bihar",
    "dulha dulhan saman delivery",
    "wedding grocery delivery bihar",
    "shaadi ka rashon online",
    "vivah samagri online bihar",
    "wedding return gifts delivery",
    "shaadi mein kaam aane wala saman",
    "wedding catering supplies bihar",
    "tent decoration delivery bihar",

    // Baby & Kids
    "baby products online bihar",
    "baby diapers delivery bihar",
    "baby food online order bihar",
    "cerelac delivery home bihar",
    "baby formula milk online",
    "baby soap shampoo delivery",
    "kids snacks online bihar",
    "baby care products bihar",
    "infant products delivery patna",
    "johnson baby products online",
    "mamy poko pants delivery",
    "baby wipes online bihar",

    // Pet Supplies
    "pet food delivery bihar",
    "dog food online order bihar",
    "cat food delivery patna",
    "pedigree dog food online",
    "whiskas cat food delivery",
    "pet care products bihar",
    "dog accessories online bihar",
    "pet grooming products delivery",

    // ==================
    // LOCATION KEYWORDS
    // ==================

    // Bihar Districts
    "grocery delivery patna",
    "grocery delivery muzaffarpur",
    "grocery delivery gaya",
    "grocery delivery bhagalpur",
    "grocery delivery darbhanga",
    "grocery delivery purnia",
    "grocery delivery begusarai",
    "grocery delivery madhubani",
    "grocery delivery samastipur",
    "grocery delivery sitamarhi",
    "grocery delivery siwan",
    "grocery delivery gopalganj",
    "grocery delivery vaishali",
    "grocery delivery nalanda",
    "grocery delivery rohtas",
    "grocery delivery buxar",
    "grocery delivery bhojpur",
    "grocery delivery munger",
    "grocery delivery katihar",
    "grocery delivery kishanganj",
    "grocery delivery supaul",
    "grocery delivery darbhanga",
    "grocery delivery araria",
    "grocery delivery madhepura",
    "grocery delivery saharsa",
    "grocery delivery khagaria",
    "grocery delivery jamui",
    "grocery delivery banka",
    "grocery delivery nawada",
    "grocery delivery aurangabad bihar",
    "grocery delivery jehanabad",
    "grocery delivery arwal",
    "grocery delivery sheohar",
    "grocery delivery sheikhpura",
    "grocery delivery lakhisarai",
    "grocery delivery kaimur",
    "grocery delivery rohtas",
    "grocery delivery motihari",
    "grocery delivery bettiah",

    // Major Cities
    "online grocery patna city",
    "grocery delivery rajendra nagar patna",
    "grocery delivery boring road patna",
    "grocery delivery kankarbagh patna",
    "grocery delivery bailey road patna",
    "grocery delivery hajipur",
    "grocery delivery danapur",
    "grocery delivery phulwari sharif",
    "grocery delivery arrah",
    "grocery delivery sasaram",
    "grocery delivery dehri",
    "grocery delivery biharsharif",
    "grocery delivery rajgir",
    "grocery delivery bodh gaya",
    "grocery delivery chhapra",
    "grocery delivery motihari",
    "grocery delivery bettiah",
    "grocery delivery raxaul",
    "grocery delivery forbesganj",
    "grocery delivery supaul town",
    "grocery delivery saharsa town",

    // Neighbouring States
    "grocery delivery varanasi",
    "grocery delivery gorakhpur",
    "grocery delivery lucknow",
    "grocery delivery allahabad",
    "grocery delivery dhanbad",
    "grocery delivery ranchi",
    "grocery delivery jamshedpur",
    "online grocery UP border",
    "grocery delivery purvanchal",
    "grocery delivery jharkhand border",

    // ==================
    // COMPETITOR KEYWORDS
    // ==================
    "blinkit alternative bihar",
    "zepto alternative bihar",
    "swiggy instamart bihar",
    "dunzo alternative bihar",
    "bigbasket alternative bihar",
    "grofers alternative bihar",
    "quick commerce bihar",
    "instant delivery bihar",
    "10 minute delivery bihar",
    "hyperlocal delivery bihar",

    // ==================
    // HINDI KEYWORDS
    // ==================
    "घर बैठे किराना मंगाओ",
    "ऑनलाइन सब्जी मंगाओ बिहार",
    "सस्ता राशन ऑनलाइन बिहार",
    "30 मिनट में डिलीवरी",
    "बाजार से सस्ता ऑनलाइन",
    "किरानासे ऐप",
    "ताजा दूध होम डिलीवरी",
    "शादी का सामान ऑनलाइन",
    "ऑनलाइन किराना स्टोर बिहार",
    "घर बैठे खरीदारी बिहार",
    "सबसे सस्ता ऑनलाइन बिहार",
    "फ्री डिलीवरी बिहार",
    "इलेक्ट्रॉनिक्स होम डिलीवरी बिहार",

    // ==================
    // GENERAL KEYWORDS
    // ==================
    "kiranase",
    "online grocery delivery bihar",
    "grocery home delivery bihar",
    "online kirana store bihar",
    "30 minute delivery bihar",
    "same day delivery bihar",
    "free delivery above 299",
    "7000 products online",
    "fastest delivery bihar",
    "best grocery app bihar",
    "grocery delivery india",
    "online shopping bihar",
    "electronics delivery bihar",
    "home delivery bihar",
  ].join(", "),
  path: "/",
});
