export enum ReturnReason {
  DAMAGED = 'DAMAGED',
  WRONG_ITEM = 'WRONG_ITEM',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  DEFECTIVE = 'DEFECTIVE',
  SIZE_ISSUE = 'SIZE_ISSUE',
  CHANGED_MIND = 'CHANGED_MIND',
  OTHER = 'OTHER',
}

export enum ReturnRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
  PICKED_UP = 'PICKED_UP',
  RECEIVED_AT_WAREHOUSE = 'RECEIVED_AT_WAREHOUSE',
  QC_PASSED = 'QC_PASSED',
  QC_FAILED = 'QC_FAILED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  FAILED_PICKUP = 'FAILED_PICKUP',
  PICKUP_OTP_PENDING = 'PICKUP_OTP_PENDING',
  CLOSED = 'CLOSED',
}

export enum QcGrade {
  RESELLABLE = 'RESELLABLE',
  REFURBISH = 'REFURBISH',
  DISPOSE = 'DISPOSE',
}
